# Generated by Django 3.1.7 on 2021-04-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210402_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
